name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      email:
        description: 'email'
        required: true
      id:
        description: 'id'
        required: true
      target:
        description: 'target'
        required: true
jobs:
  zap_from_api:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Email: ${{ github.event.inputs.email }}"
          echo "Id: ${{ github.event.inputs.id }}"
          echo "Target: ${{ github.event.inputs.target }}"
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: '${{ github.event.inputs.target }}'
          issue_title: '${{ github.event.inputs.id }}${{ github.event.inputs.email }}'
